In [1]:
# Importing the python image library to load in .tiffs
from PIL import Image
import numpy as np
import os

import numpy as np
import ipywidgets as widgets
from IPython.display import display
import matplotlib.pyplot as plt

In [2]:
# LOADING THE TIFFS
# Load in a single image
singleImage = Image.open("test.tif")
# Turn this image into an array
singleImageArray = np.asarray(singleImage)


In [3]:
# We know that we can turn one image into an array...can we stack all the images for a thin section into one, 3D array?

# Create an array that will contain each thin section

thinSections = []

iteration = 0

# Okay, for every folder in our parent folder
for root, dirs, files in os.walk('./Aikin Data/'):
        # Does the directory contain the word RAW?
        if "RAW" in root:
            # If so, what is the name of the thin section?
            thinSectionName = os.path.basename(os.path.dirname(root))
            thinSections.append(dict({'name': thinSectionName}))
            numberOfFiles = len(files)
            if numberOfFiles > 0:
                arraySet = False
                tsArray = []
                sectionCount = 0
                for file in files:
                    tsImage = Image.open(os.path.join(root, file))
                    singleImageArray = np.asarray(tsImage)
                    if not arraySet:
                        tsShape = singleImageArray.shape
                        tsArray = np.empty([tsShape[0], tsShape[1], numberOfFiles])
                        arraySet = True
                    tsArray[:, :, sectionCount] = singleImageArray
                    sectionCount = sectionCount + 1
                thinSections[iteration]['stack'] = tsArray
            iteration = iteration + 1
            for file in files:
                print(os.path.join(root, file))



./Aikin Data/78.7-10-1_Hot\RAW\UGG-W3-87.7-10.1-Full_Al Ka_Al Ka EDS.Tiff
./Aikin Data/78.7-10-1_Hot\RAW\UGG-W3-87.7-10.1-Full_Ca Ka_Ca Ka EDS.Tiff
./Aikin Data/78.7-10-1_Hot\RAW\UGG-W3-87.7-10.1-Full_Ce La_Ce La (Sp 2).Tiff
./Aikin Data/78.7-10-1_Hot\RAW\UGG-W3-87.7-10.1-Full_Fe Ka_Fe Ka EDS.Tiff
./Aikin Data/78.7-10-1_Hot\RAW\UGG-W3-87.7-10.1-Full_K  Ka_K  Ka EDS.Tiff
./Aikin Data/78.7-10-1_Hot\RAW\UGG-W3-87.7-10.1-Full_Mg Ka_Mg Ka (Sp 4).Tiff
./Aikin Data/78.7-10-1_Hot\RAW\UGG-W3-87.7-10.1-Full_Si Ka_Si Ka EDS.Tiff
./Aikin Data/78.7-10-1_Hot\RAW\UGG-W3-87.7-10.1-Full_Ti Ka_Ti Ka (Sp 5).Tiff
./Aikin Data/78.7-10-1_Hot\RAW\UGG-W3-87.7-10.1-Full_Y  La_Y  La (Sp 1).Tiff
./Aikin Data/78.7-10-1_Hot\RAW\UGG-W3-87.7-10.1-Full_Zr La_Zr La (Sp 3).Tiff
./Aikin Data/78.7-10-2_Hot\RAW\UGG-W3-78.7-10-Al Ka EDS.tiff
./Aikin Data/78.7-10-2_Hot\RAW\UGG-W3-78.7-10-Ca Ka EDS.tiff
./Aikin Data/78.7-10-2_Hot\RAW\UGG-W3-78.7-10-Ce La (Sp 2).tiff
./Aikin Data/78.7-10-2_Hot\RAW\UGG-W3-78.7-10-Fe Ka EDS.tif

In [4]:
thinSections

[{'name': '78.7-10-1_Hot',
  'stack': array([[[ 81.        ,  48.        ,   5.        , ...,   3.        ,
            19.        ,   0.        ],
          [ 90.        ,  47.        ,   4.        , ...,   3.        ,
            13.        ,   0.        ],
          [ 72.        ,  49.        ,   7.        , ...,   4.        ,
            11.        ,   0.        ],
          ...,
          [382.        ,  58.        ,   4.        , ...,  58.        ,
            13.        ,   1.        ],
          [372.        ,  78.        ,   1.        , ...,  44.        ,
            13.        ,   0.        ],
          [366.        ,  68.        ,   0.        , ...,  57.        ,
             2.        ,   1.        ]],
  
         [[ 94.        ,  46.        ,   5.        , ...,   4.        ,
            18.        ,   0.        ],
          [101.        ,  41.        ,   5.        , ...,   3.        ,
            13.        ,   0.        ],
          [ 88.        ,  51.        ,   3.      

In [5]:
thisThinSection = thinSections[0]
stack =  thisThinSection['stack']
stackShape = stack.shape

# Create a drop down to pick the right thin section


# Create dropdown widgets for the three dimensions
channel1Dropdown = widgets.Dropdown(
    options=range(stackShape[2]),
    description='Channel 1:'
)

channel2Dropdown = widgets.Dropdown(
    options=range(stackShape[2]),
    description='Channel 2:'
)

channel3Dropdown = widgets.Dropdown(
    options=range(stackShape[2]),
    description='Channel 3:'
)

# Create a button widget to trigger visualization
visualizeBtn = widgets.Button(
    description='Visualize',
    disabled=False,
    button_style='',  # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Click to visualize',
    icon='check'
)

# Create an output widget to display the image
output = widgets.Output()

def visualize(b):

    recastThinSection = np.empty([stackShape[0], stackShape[1], 3], dtype='int')

    recastThinSection[:,:,0] = stack[:,:,channel1Dropdown.value]
    recastThinSection[:,:,1] = stack[:,:,channel2Dropdown.value]
    recastThinSection[:,:,2] = stack[:,:,channel3Dropdown.value]

    print(recastThinSection)

    # Display the image using Matplotlib
    with output:
        output.clear_output()
        plt.figure(figsize=(8, 6))
        plt.imshow(recastThinSection)  # You can change the colormap as needed
        plt.show()

# Connect the button's click event to the visualization function
visualizeBtn.on_click(visualize)

# Display the widgets
display(channel1Dropdown, channel2Dropdown, channel3Dropdown, visualizeBtn)
display(output)

Dropdown(description='Channel 1:', options=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9), value=0)

Dropdown(description='Channel 2:', options=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9), value=0)

Dropdown(description='Channel 3:', options=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9), value=0)

Button(description='Visualize', icon='check', style=ButtonStyle(), tooltip='Click to visualize')

Output()

[[[ 20   5   3]
  [ 20   4   3]
  [ 21   7   4]
  ...
  [ 60   4  58]
  [ 68   1  44]
  [ 62   0  57]]

 [[ 13   5   4]
  [ 13   5   3]
  [ 13   3   2]
  ...
  [ 32   5  25]
  [ 37   0  44]
  [ 61   0  61]]

 [[ 16   4   3]
  [ 16   7   0]
  [ 16   5   1]
  ...
  [ 44   8  15]
  [ 28   2  14]
  [ 20   0  21]]

 ...

 [[ 15   8  26]
  [ 15   8  24]
  [ 16   8  49]
  ...
  [ 16   4   1]
  [ 17   4   2]
  [ 22   1   3]]

 [[ 33  11  25]
  [ 20   6  61]
  [ 47   9 122]
  ...
  [ 11   2   4]
  [ 16   1   5]
  [ 22   0   4]]

 [[ 25   9  54]
  [ 27   3  19]
  [ 23   2   8]
  ...
  [ 16   2   0]
  [ 14   1   2]
  [ 11   0   2]]]
